// SPDX-License-Identifier: MIT
 
pragma solidity =0.8.19;
 
contract CheckExtCodeSize {

   function checkBatchYul(uint256 l) external returns (uint256 length) {
        address a = 0x0000000000000000000000000000000000010000;
        uint256 len = l / 100;
        for (uint256 i; i<len; i++) {
            assembly {
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)   
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)
               length := extcodesize(a)                                                                                                                                 
            }
        }
        return length;
    }
}
